### ISSUE TITLE
(SyntaxError) while using the library. version_commands.rb:51: syntax error, unexpected '.' 

### ISSUE THREAD

**Issue by nithish-thomas** [pact-foundation/pact_broker-client#109]
Our build system is throwing the below error while trying to use the library

/07 04:42:37 [ERROR] service:                 branch_name: options.branch&.strip,
/07 04:42:37 [ERROR] service:                                                                    ^

No idea on ruby syntax but is the '&' supposed to be there.

https://github.com/pact-foundation/pact_broker-client/blob/55668a9ae661f82c8fd4df520d1bb287cb3e91ce/lib/pact_broker/client/cli/version_commands.rb#L51

**Comment by YOU54F** [comment]
Hi @nithish-thomas 

Could you try [pact-1.88.83](https://github.com/pact-foundation/pact-ruby-standalone/releases/tag/v1.88.83)

https://github.com/pact-foundation/pact-ruby-standalone/issues/72

We will get this sorted asap

**Comment by YOU54F** [comment]
Hey,

This is fixed now, tested in the ruby standalone

```
**curl -LO https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.88.85/pact-1.88.84-osx.tar.gz
tar xzf pact-1.88.84-osx.tar.gz
cd pact/bin
./pact-broker can-i-deploy
```

Result:

```
/Users/yousaf.nabi/dev/pact-foundation/pact_broker-client/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact_broker-client-1.61.0/lib/pact_broker/client/cli/broker.rb:8:in `require': /Users/yousaf.nabi/dev/pact-foundation/pact_broker-client/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact_broker-client-1.61.0/lib/pact_broker/client/cli/version_commands.rb:51: syntax error, unexpected '.' (SyntaxError)
                branch_name: options.branch&.strip,
                                             ^
/Users/yousaf.nabi/dev/pact-foundation/pact_broker-client/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact_broker-client-1.61.0/lib/pact_broker/client/cli/version_commands.rb:52: syntax error, unexpected '.'
                tags: options.tag&.collect(&:strip)
                                   ^
/Users/yousaf.nabi/dev/pact-foundation/pact_broker-client/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact_broker-client-1.61.0/lib/pact_broker/client/cli/version_commands.rb:53: syntax error, unexpected '}', expecting keyword_end
        from /Users/yousaf.nabi/dev/pact-foundation/pact_broker-client/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact_broker-client-1.61.0/lib/pact_broker/client/cli/broker.rb:8:in `<top (required)>'
        from /Users/yousaf.nabi/dev/pact-foundation/pact_broker-client/pact/bin/pact/lib/app/pact-broker.rb:1:in `require'
        from /Users/yousaf.nabi/dev/pact-foundation/pact_broker-client/pact/bin/pact/lib/app/pact-broker.rb:1:in `<main>
```


Post

```sh
curl -LO https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.88.85/pact-1.88.85-osx.tar.gz
tar xzf pact-1.88.85-osx.tar.gz
cd pact/bin
./pact-broker can-i-deploy
```

Result

```sh
No value provided for required options '--pacticipant'
```

**Comment by bethesque** [comment]
You're a champion @YOU54F
