### ISSUE TITLE
create-webhook - NoMethodError: undefined method `post' for nil:NilClass

### ISSUE THREAD

**Issue by anjakammer** [pact-foundation/pact_broker-client#60]
Using the container image  `pactfoundation/pact-cli:latest` and I get:

```
broker create-webhook http://myci.com -X POST -H 'Content-Type: application/json' -d '{"key":"${pact.value}"}' --contract-content-changed -u=pact-broker -p=$BA_PASS
NoMethodError: undefined method `post' for nil:NilClass
  /usr/lib/ruby/gems/2.5.0/gems/pact_broker-client-1.20.0/lib/pact_broker/client/webhooks/create.rb:44:in `create_webhook_with_optional_consumer_and_provider'
  /usr/lib/ruby/gems/2.5.0/gems/pact_broker-client-1.20.0/lib/pact_broker/client/webhooks/create.rb:30:in `call'
  /usr/lib/ruby/gems/2.5.0/gems/pact_broker-client-1.20.0/lib/pact_broker/client/webhooks/create.rb:17:in `call'
  /usr/lib/ruby/gems/2.5.0/gems/pact_broker-client-1.20.0/lib/pact_broker/client/cli/broker.rb:167:in `create_webhook'
  /usr/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /usr/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /usr/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /usr/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  /usr/lib/ruby/gems/2.5.0/gems/pact_broker-client-1.20.0/lib/pact_broker/client/cli/custom_thor.rb:15:in `start'
  /pact/lib/pact/cli.rb:34:in `broker'
  /usr/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /usr/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /usr/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
  /usr/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
  bin/pact:9:in `<top (required)>'
```

When I set the credentials via env vars for the container, it works.

**Comment by anjakammer** [comment]
Great, thank you!
When do you plan to release a new version with the fix?

**Comment by bethesque** [comment]
It's actually not so much a fix as removing a shortcut option conflict. Use `--broker-username` instead of `-u` because the `-u` conflicts with the `-u` from the curl command.
