### ISSUE TITLE
pact-broker create-webhook: cannot load such file -- pact/hal/entity (LoadError)

### ISSUE THREAD

**Issue by castarco** [pact-foundation/pact_broker-client#67]
Hi, I installed the pact broker client this way (I'm on Ubuntu 19.10, with Ruby 2.5):
```bash
gem install pact_broker-client;
```

And tried to create a webhook with a command like this one:
```bash
pact-broker create-webhook "${CONSUMER_PIPELINE_WEBHOOK}" \
      --request POST \
      --consumer "${CONSUMER}" \
      --provider "${PROVIDER}" \
      --provider-verification-published \
      --broker-username "${HTTP_BASIC_AUTH_USERNAME}" \
      --broker-password "${HTTP_BASIC_AUTH_PASSWORD}" \
      --broker-base-url "${BROKER_BASE_URL}";
```

But I get the following error:
```
Traceback (most recent call last):
        16: from /usr/local/bin/pact-broker:23:in `<main>'
        15: from /usr/local/bin/pact-broker:23:in `load'
        14: from /var/lib/gems/2.5.0/gems/pact_broker-client-1.25.0/bin/pact-broker:4:in `<top (required)>'
        13: from /var/lib/gems/2.5.0/gems/pact_broker-client-1.25.0/lib/pact_broker/client/cli/custom_thor.rb:15:in `start'
        12: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        11: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        10: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
         9: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
         8: from /var/lib/gems/2.5.0/gems/pact_broker-client-1.25.0/lib/pact_broker/client/cli/broker.rb:121:in `create_webhook'
         7: from /var/lib/gems/2.5.0/gems/pact_broker-client-1.25.0/lib/pact_broker/client/cli/broker.rb:269:in `run_webhook_commands'
         6: from /var/lib/gems/2.5.0/gems/pact_broker-client-1.25.0/lib/pact_broker/client/webhooks/create.rb:17:in `call'
         5: from /var/lib/gems/2.5.0/gems/pact_broker-client-1.25.0/lib/pact_broker/client/webhooks/create.rb:28:in `call'
         4: from /var/lib/gems/2.5.0/gems/pact_broker-client-1.25.0/lib/pact_broker/client/webhooks/create.rb:39:in `create_webhook_with_consumer_and_provider'
         3: from /var/lib/gems/2.5.0/gems/pact_broker-client-1.25.0/lib/pact_broker/client/hal/link.rb:53:in `post'
         2: from /var/lib/gems/2.5.0/gems/pact_broker-client-1.25.0/lib/pact_broker/client/hal/link.rb:65:in `wrap_response'
         1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- pact/hal/entity (LoadError)
```

I'm not sure if this is due to me passing some incorrect argument (although the error should be different in that case), due to a missing dependency, or due to a bug.

**Comment by bethesque** [comment]
There's an underlying error coming back from the broker, and it's blowing up in the error handling code. I've just put out a fix for the require. Upgrade to 1.25.1.
